# Generated by Django 4.2.9 on 2026-01-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('times_practiced', models.PositiveIntegerField(default=0, verbose_name='Vezes Praticadas')),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Prática')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Progresso de Lição',
                'verbose_name_plural': 'Progressos de Lições',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons_completed', models.PositiveIntegerField(default=0, verbose_name='Total de Lições Completadas')),
                ('total_vocabulary_mastered', models.PositiveIntegerField(default=0, verbose_name='Total de Vocabulário Dominado')),
                ('overall_accuracy', models.DecimalField(decimal_places=2, default=0.0, help_text='Será calculado na Fase 3 com pronunciation assessment', max_digits=5, verbose_name='Acurácia Geral')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Progresso do Usuário',
                'verbose_name_plural': 'Progressos dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='VocabularyMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Básico'), (3, 'Intermediário'), (4, 'Proficiente'), (5, 'Mestre')], default=1, verbose_name='Nível de Domínio')),
                ('times_reviewed', models.PositiveIntegerField(default=0, verbose_name='Vezes Revisadas')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Revisão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domínio de Vocabulário',
                'verbose_name_plural': 'Domínios de Vocabulário',
            },
        ),
    ]
