# Generated by Django 4.2.9 on 2026-01-29 11:46

import apps.audio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(choices=[('lesson', 'Lição'), ('vocabulary', 'Vocabulário')], max_length=20, verbose_name='Tipo de Áudio')),
                ('audio_file', models.FileField(upload_to='audio/%Y/%m/', validators=[apps.audio.models.validate_audio_extension], verbose_name='Arquivo de Áudio')),
                ('description', models.CharField(blank=True, help_text='Descrição opcional do áudio', max_length=200, verbose_name='Descrição')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duração do áudio em segundos (opcional)', null=True, verbose_name='Duração (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='lessons.lesson', verbose_name='Lição')),
                ('vocabulary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='lessons.vocabularyitem', verbose_name='Vocabulário')),
            ],
            options={
                'verbose_name': 'Arquivo de Áudio',
                'verbose_name_plural': 'Arquivos de Áudio',
                'ordering': ['-created_at'],
            },
        ),
    ]
