# Generated by Django 4.2.9 on 2026-01-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeltLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_korean', models.CharField(help_text='Nome da faixa em Hangul (ex: 흰띠)', max_length=50, verbose_name='Nome em Coreano')),
                ('name_portuguese', models.CharField(help_text='Nome da faixa em português (ex: Branca)', max_length=50, verbose_name='Nome em Português')),
                ('order', models.PositiveIntegerField(help_text='Ordem de progressão (1=primeira faixa, 8=última)', unique=True, verbose_name='Ordem')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional da faixa', verbose_name='Descrição')),
                ('min_lessons_completed', models.PositiveIntegerField(default=0, help_text='Número mínimo de lições que devem ser completadas para avançar desta faixa', verbose_name='Mínimo de Lições Completadas')),
                ('min_vocabulary_mastered', models.PositiveIntegerField(default=0, help_text='Número mínimo de vocabulário dominado para avançar desta faixa', verbose_name='Mínimo de Vocabulário Dominado')),
                ('min_accuracy_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Acurácia mínima (0-100) para avançar desta faixa. Usado na Fase 3.', max_digits=5, verbose_name='Porcentagem Mínima de Acurácia')),
            ],
            options={
                'verbose_name': 'Nível de Faixa',
                'verbose_name_plural': 'Níveis de Faixa',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_korean', models.CharField(help_text='Título da lição em Hangul', max_length=200, verbose_name='Título em Coreano')),
                ('title_portuguese', models.CharField(help_text='Título da lição em português', max_length=200, verbose_name='Título em Português')),
                ('order_in_belt', models.PositiveIntegerField(help_text='Ordem da lição dentro da faixa', verbose_name='Ordem na Faixa')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional da lição', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('belt_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.beltlevel', verbose_name='Nível de Faixa')),
            ],
            options={
                'verbose_name': 'Lição',
                'verbose_name_plural': 'Lições',
                'ordering': ['belt_level__order', 'order_in_belt'],
                'unique_together': {('belt_level', 'order_in_belt')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean_text', models.CharField(help_text='Palavra ou frase em Hangul (SEM romanização)', max_length=100, verbose_name='Texto em Coreano')),
                ('portuguese_translation', models.CharField(help_text='Tradução para português', max_length=200, verbose_name='Tradução em Português')),
                ('context', models.TextField(blank=True, help_text='Contexto de uso (opcional)', verbose_name='Contexto')),
                ('example_sentence_korean', models.TextField(blank=True, help_text='Frase de exemplo em Hangul (opcional)', verbose_name='Exemplo em Coreano')),
                ('example_sentence_portuguese', models.TextField(blank=True, help_text='Tradução do exemplo (opcional)', verbose_name='Exemplo em Português')),
                ('difficulty', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado')], default=1, verbose_name='Dificuldade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lessons', models.ManyToManyField(related_name='vocabulary_items', to='lessons.lesson', verbose_name='Lições')),
            ],
            options={
                'verbose_name': 'Item de Vocabulário',
                'verbose_name_plural': 'Itens de Vocabulário',
                'ordering': ['korean_text'],
            },
        ),
    ]
